// Writes a small placeholder public/cards.json so the app runs before the real
// data has been generated by scripts/build-cards.mjs.
import { writeFileSync } from 'node:fs';

const fp = (f, w = 500) => `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(f)}?width=${w}`;
const wp = (t) => `https://fr.wikipedia.org/wiki/${encodeURIComponent(t.replace(/ /g, '_'))}`;

const raw = [
  ['Q517', 'Napoléon Ier', 'Empereur des Français (1769-1821)', 'Jacques-Louis David - The Emperor Napoleon in His Study at the Tuileries - Google Art Project.jpg', 5, 'Napoleon signature.svg'],
  ['Q362', 'Seconde Guerre mondiale', 'Conflit armé planétaire (1939-1945)', 'Into the Jaws of Death 23-0455M edit.jpg', 5],
  ['Q7226', 'Louis XIV', 'Roi de France et de Navarre (1638-1715)', 'Louis XIV of France.jpg', 4],
  ['Q7322', 'Jeanne d’Arc', 'Héroïne de l’histoire de France (1412-1431)', 'Joan of Arc miniature graded.jpg', 4],
  ['Q1048', 'Jules César', 'Général et homme d’État romain (-100 à -44)', 'Retrato de Julio César (26724093101).jpg', 4],
  ['Q8409', 'Alexandre le Grand', 'Roi de Macédoine (-356 à -323)', 'Alexander the Great mosaic.jpg', 3],
  ['Q635', 'Cléopâtre VII', 'Dernière reine d’Égypte ptolémaïque (-69 à -30)', 'Kleopatra-VII.-Altes-Museum-Berlin1.jpg', 3],
  ['Q8023', 'Winston Churchill', 'Premier ministre du Royaume-Uni (1874-1965)', 'Sir Winston Churchill - 19086236948.jpg', 3, 'Sir Winston Churchill Signature.svg'],
  ['Q91', 'Abraham Lincoln', '16e président des États-Unis (1809-1865)', 'Abraham Lincoln O-77 matte collodion print.jpg', 3, 'Abraham Lincoln Signature.svg'],
  ['Q2383', 'Charles de Gaulle', 'Président de la République française (1890-1970)', 'De Gaulle-OWI.jpg', 3],
  ['Q720', 'Gengis Khan', 'Fondateur de l’Empire mongol (v. 1162-1227)', 'YuanEmperorAlbumGenghisPortrait.jpg', 2],
  ['Q1001', 'Gandhi', 'Guide spirituel de l’indépendance indienne (1869-1948)', 'Mahatma-Gandhi, studio, 1931.jpg', 2],
  ['Q1394', 'Lénine', 'Révolutionnaire et dirigeant soviétique (1870-1924)', 'Vladimir Lenin.jpg', 2],
  ['Q44292', 'Maximilien de Robespierre', 'Révolutionnaire français (1758-1794)', 'Robespierre.jpg', 2],
  ['Q48314', 'Bataille de Waterloo', 'Dernière bataille de Napoléon (18 juin 1815)', 'Battle of Waterloo 1815.PNG', 2],
  ['Q7937', 'Christophe Colomb', 'Navigateur génois (1451-1506)', 'Portrait of a Man, Said to be Christopher Columbus.jpg', 1],
  ['Q2280', 'Empire romain', 'État de l’Antiquité (-27 à 476)', 'Roman Empire Trajan 117AD.png', 1],
  ['Q160112', 'Bataille d’Austerlitz', 'Victoire de Napoléon sur l’Autriche et la Russie (1805)', 'La bataille d\'Austerlitz. 2 decembre 1805 (François Gérard).jpg', 1],
  ['Q5086', 'Mur de Berlin', 'Frontière fortifiée de Berlin (1961-1989)', 'Berlinermauer.jpg', 1],
  ['Q193272', 'Siège d’Alésia', 'Victoire de César sur Vercingétorix (-52)', 'Siege-alesia-vercingetorix-jules-cesar.jpg', 0],
  ['Q12418', 'Toutânkhamon', 'Pharaon de la XVIIIe dynastie', 'CairoEgMuseumTaaMaskMostlyPhotographed.jpg', 0],
  ['Q193314', 'Prise de la Bastille', 'Journée révolutionnaire du 14 juillet 1789', 'Anonymous - Prise de la Bastille.jpg', 0],
  ['Q9696', 'Vercingétorix', 'Chef gaulois des Arvernes (v. -80 à -46)', 'Vercingetorix stater Gallica.jpg', 0],
  ['S24', 'Bataille de Marignan', 'Victoire de François Ier (1515)', 'Bataille de Marignan.jpg', 0],
  ['S25', 'Guerre de Cent Ans', 'Conflit franco-anglais (1337-1453)', 'Battle of crecy froissart.jpg', 0],
];

const cards = raw.map(([id, t, d, img, r, sig], i) => ({
  id, n: i + 1, t, d, img: fp(img), ...(sig ? { sig: fp(sig, 400) } : {}), views: Math.round(2_000_000 / (i + 1)), r, url: wp(t),
}));
cards[0].alt = fp('Napoleon Bonaparte - Jacques-Louis David - The Crossing of the Saint-Bernard Pass.jpg');

writeFileSync('public/cards.json', JSON.stringify({ version: 1, generatedAt: new Date().toISOString(), sample: true, cards }));
console.log(`sample: ${cards.length} cards`);
